Keepout areas for cris_new_area_fixed
hsp-iit/tour-guide-robot pull request #19
Opened 2022-11-14 11:17 UTC by morpheus1820

2022-11-15 13:57 UTC, ste93 requested changes

2022-11-15 13:57 UTC, ste93 commented on app/maps/cris_new_area_fixed_keepout_mask.yaml
> +origin: [-100.000000, -100.000000, 0.000000]
```suggestion
origin: [-13.1, -7.62, 0]
```

2022-11-15 13:57 UTC, ste93 commented on app/navigation2/conf/cris_new_area_fixed_keepout_params.yaml
> +    use_sim_time: true
```suggestion
```

2022-11-15 13:57 UTC, ste93 commented on app/navigation2/conf/cris_new_area_fixed_keepout_params.yaml
> +    use_sim_time: true
```suggestion
```

2022-11-15 13:57 UTC, ste93 commented on app/navigation2/conf/nav2_params.yaml
> +        filter_info_topic: "/costmap_filter_info"controller_server_rclcpp_node:
```suggestion
controller_server_rclcpp_node:
```

2022-11-15 13:57 UTC, ste93 commented on app/navigation2/conf/nav2_params.yaml
> +      keepout_filter:
```suggestion
      filters: ["keepout_filter"]
      keepout_filter:
```

2022-11-15 13:57 UTC, ste93 commented on app/navigation2/launch/costmap_filter_info.launch.py
> +        default_value='true',
```suggestion
        default_value='false',
```

2022-11-15 14:37 UTC, ste93 commented
also add in `app/navigation2/scripts/Navigation_ROS2_R1SN003.xml` the following code at line 92
```
   <module>
      <name>ros2</name>
      <parameters>launch launch/costmap_filter_info.launch.py params_file:=conf/cris_new_area_fixed_keepout_params.yaml mask:=/home/user1/tour-guide-robot/app/maps/cris_new_area_fixed_keepout_mask.yaml</parameters>
      <workdir>/home/user1/tour-guide-robot/app/navigation2/</workdir>
      <node>console</node>
   </module>
```

2022-11-18 13:45 UTC, elandini84 commented
Hi @morpheus1820, can you apply the changes suggested by @ste93 so we can proceed with rebasing and merging the PR?

2022-11-18 14:10 UTC, morpheus1820 commented
> Hi @morpheus1820, can you apply the changes suggested by @ste93 so we can proceed with rebasing and merging the PR?

done

2022-11-18 14:33 UTC, elandini84 commented
> Hi @morpheus1820, can you apply the changes suggested by @ste93 so we can proceed with rebasing and merging the PR?

Ok, can you rebase it on ros2 branch? The branch is currently 15 commits behind [origin/ros2](https://github.com/hsp-iit/tour-guide-robot)

2022-11-18 15:27 UTC, closed without merging